### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'sha3_var1'

### ISSUE THREAD

**Issue by acmLL** [a16z/halmos#30] opened 2023-02-13 10:42 UTC
Running 9 tests for test/Vault.t.sol:SandclockLUSDTest
Traceback (most recent call last):
  File "/Users/alexandremota/Library/Python/3.9/bin/halmos", line 8, in <module>
    sys.exit(main())
  File "/Users/alexandremota/Library/Python/3.9/lib/python/site-packages/halmos/__main__.py", line 445, in main
    exitcode = run(hexcode, abi, srcmap, srcs, funname, funsig, funselector, arrlen, args, setup, options)
  File "/Users/alexandremota/Library/Python/3.9/lib/python/site-packages/halmos/__main__.py", line 215, in run
    (setup_exs, setup_steps) = sevm.run(setup_ex)
  File "/Users/alexandremota/Library/Python/3.9/lib/python/site-packages/halmos/sevm.py", line 962, in run
    self.create(ex, stack, step_id, out)
  File "/Users/alexandremota/Library/Python/3.9/lib/python/site-packages/halmos/sevm.py", line 649, in create
    (new_exs, new_steps) = self.run(self.mk_exec(
  File "/Users/alexandremota/Library/Python/3.9/lib/python/site-packages/halmos/sevm.py", line 977, in run
    ex.sstore(ex.st.pop(), ex.st.pop())
  File "/Users/alexandremota/Library/Python/3.9/lib/python/site-packages/halmos/sevm.py", line 256, in sstore
    slot, keys = int(str(offsets[0])), offsets[1:]
ValueError: invalid literal for int() with base 10: 'sha3_var1'

**Comment by daejunpark** [comment] 2023-03-07 19:28
This relates to decoding the hashed storage slot layout, which can be challenging due to technical complexities. As such, decoding failures can occur for various reasons. If you could provide a reproducible example, it would be helpful in allowing us to investigate the issue further.

**Comment by acmLL** [comment] 2023-04-13 16:24
I am sorry. I do not have such a situation anymore. But I opened up other issues with attached examples. Thanks! Maybe you can close this one

**Comment by thedavidmeister** [comment] 2023-04-22 13:51
Here's a repro in CI for this error, without any storage slot.

`ValueError: invalid literal for int() with base 10: 'Concat(0, Extract(7, 0, p_length_uint8))'`

https://github.com/rainprotocol/sol.lib.memory/actions/runs/4773082721/jobs/8485943652?pr=2

**Comment by daejunpark** [comment] 2023-05-12 21:44
@thedavidmeister thanks for providing the repro!  Your tests are also very interesting.

The latest master version should fix the uncaught exception issue, but several of your test functions are not supported due to the use of dynamic arrays. Halmos is not currently designed to support dynamic arrays for performance reasons, so you will need to refactor your existing tests to use fixed-size arrays instead. In the current design, the size of arrays (including bytes) must be given as a concrete value, while the individual elements can be symbolic.

**Comment by daejunpark** [comment] 2023-05-12 21:47
I will close this issue for now. Please feel free to reopen it if you still encounter similar problems. Thanks!

**Closed by daejunpark** 2023-05-12 21:47 UTC
Labels: bug
