### ISSUE TITLE
Halmos thinks all paths will revert even though I can hardcode a counter example, due to loops

### ISSUE THREAD

**Issue by GalloDaSballo** [a16z/halmos#327] opened 2024-07-22 16:50 UTC
**Describe the bug**
I run 
```bash
halmos --mc CryticTester
```
In this repo:
https://github.com/GalloDaSballo/halmos-loop-bug-repro

It fails with:
```solidity
WARNING:Halmos:check_counter_symbolic(bytes4[],(uint256,address,address,uint256,uint256)[]): all paths have been reverted; the setup state or inputs may have been too restrictive.
```

I can run `forge test --match-test test_counterSymbolic -vv`

To reproduce a test that will pass, and doesn't revert

**To Reproduce**
Clone 
```
https://github.com/GalloDaSballo/halmos-loop-bug-repro
```

Run

```
halmos --mc CryticTester
```

**Environment:**
- MacOS
 - Python version: Python 2.7.16 
 - halmos                    0.1.13

**Additional context**

Running with
```
halmos --mc CryticTester --array-lengths selector=2,data=2 --loop 256 -vvvvv
```

Doesn't cause the message and instead allows Halmos to run the prover

**Comment by daejunpark** [comment] 2024-11-14 00:20
sorry for the delayed response. the issue is no longer reproducible in the latest version of halmos. i'm closing this now, but please feel free to reopen if the problem persists.

btw, your test looks interesting. please feel free to ping us in the halmos TG channel if you encounter any other issues. thank you!

**Closed by daejunpark** 2024-11-14 00:20 UTC
Labels: bug
